[package]
name = "cantact"
version = "0.1.0"
authors = ["Daniel Basedow <db@connectedcars.dk>"]

[dependencies]
serial = "0.4.0"
tokio-serial = "0.8.0"
bytes = "0.4"
futures = "0.1"
tokio-io = "0.1"
tokio = "0.1"
